name: build

env:
  ENV_LINUX: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v2
  ENV_WINDOWS: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 GOAMD64=v3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'
        cache: false

    - name: Initialize Go module
      run: go mod init github.com/XTLS/Xray-core

    - name: Show go env
      run: go env

    - name: git clone
      run: |
        git clone --depth 1 https://github.com/XTLS/Xray-core.git

    - name: go build
      run: | 
        cd Xray-core
        go mod download
        go env -w ${{ env.ENV_LINUX }}
        go build -v -o xray -trimpath -ldflags "-s -w -buildid=" ./main
        go env -w ${{ env.ENV_WINDOWS }}
        go build -v -o xray.exe -trimpath -ldflags "-s -w -buildid=" ./main

    - name: Upload files
      uses: actions/upload-artifact@v3
      with:
        name: xray
        path: |
          Xray-core/xray
          Xray-core/xray.exe
